services:
  - type: web
    name: supermercado-boa-compra
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: supermercado-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: supermercado-db
    plan: free
